### ISSUE TITLE
ADG715 sample code

### ISSUE THREAD

**Issue by samcontrollers** [NothinRandom/ADG715#1]
Thank you for your work on ADG715 !
Do you have a sample code of lib usage ?
Thanks

**Comment by NothinRandom** [comment]
@samcontrollers,  sorry for the late response.  US holiday yesterday, and I’ve been experiencing some power outage at the house.  Once power comes back online, I’ll take a look for you.  I think implementation was relatively straight forward.

**Comment by NothinRandom** [comment]
@samcontrollers, I looked but couldn't find anything useful for that specific IC.  Which platform are you targeting?  Maybe I can whip up something I think should theoretically work, and you can then extend from there?

**Comment by NothinRandom** [comment]
@samcontrollers, closing due to lack of response.  Go ahead and reopen when you have more info.
